(function(){function q(a){0<$(a.target).parents(".js-menuitem--dropdown").length||(r(),$(".js-menuitem--dropdown > div").hide(),g&&$(".js-menuitem--dropdown.active div.active-shadow").toggle(),g=!1)}function t(a){r();$(".js-menuitem--dropdown > div").hide();g&&$(".js-menuitem--dropdown.active div.active-shadow").toggle();g=!1}function B(a){0===$(a.target).parents(".c-dropdown").length&&$(this).parents(".js-menuitem--dropdown").find(".c-dropdown-menu").hide()}function C(a){a.keyCode==D&&(a.preventDefault(),
a.data.dropdown.hide(),$(".js-menuitem--dropdown.active div.active-shadow").show(),g=!1,a.data.button.focus())}function r(){$("body").get(0).removeEventListener(l,q,!0);$(document).off(u,t)}function v(a){a.keyCode!=w||a.shiftKey||(a.preventDefault(),a.data.focus())}function x(a){a.keyCode==w&&a.shiftKey&&(a.preventDefault(),a.data.focus())}function n(a){dropdownAttribute=a.data().dropdown;switch(dropdownAttribute){case h.Courses:return a.find(".c-dropdown--emptyState").length?a.find(".c-dropdownMenu__navigation > a:last"):
a.find("input:first");case h.Groups:return a.find("h3:first");case h.Projects:case h.YourChildren:return a.find("a:not(.c-dropdownMenu__skiplink):first")}return null}function y(a,c){var b=!1;a.each(function(a,f){-1==$(f).data().title.toString().toLowerCase().indexOf(c)?$(f).hide():($(f).show(),b=!0)});return b}function z(a,c){$column=$(c);$column.text($column.data("content")).show()}function A(a,c){$column=$(c);$column.text("").hide()}function m(a,c,b){var d=coursesSortDropdownScope.kpi;CommonFunctions.measureKpi(d.url,
d.section,d.measures[c],d.context);b=b||!1;a.sort(function(a,d){a=a.getAttribute("data-"+c).toLowerCase();d=d.getAttribute("data-"+c).toLowerCase();"title"!==c&&(a=parseInt(a),d=parseInt(d));if(b){if(a>d)return-1;if(a<d)return 1}else{if(a>d)return 1;if(a<d)return-1}return 0})}var p=!1,D=CCL.CommonConstants.keyCodes.escape,E=CCL.CommonConstants.keyCodes.enter,w=CCL.CommonConstants.keyCodes.tab,F=CCL.CommonConstants.mediaScreenSizes.mobile,g,k=$(".js-menuitem--dropdown"),h={Courses:"courses",Groups:"data-projects-dropdown",
Projects:"data-project-dropdown",YourChildren:"data-children-dropdown"};document.hideDropDowns=hideDropDowns=function(){$(".js-menuitem--dropdown > div").hide();$(".js-menuitem--dropdown.active div.active-shadow").show();$("ul.l-main-menu-items li.l-tab-menu-text a.l-main-menu-lnk").removeClass("hover")};$(".js-menuitem--dropdown > a").on("keyup",function(a){a.which==CCL.CommonConstants.keyCodes.space&&$(a.currentTarget).click()});var l=CCL.CommonFunctions.isMobileDevice()?"touchstart":"click",u=
CCL.CommonFunctions.isMobileDevice()?CommonTriggers.touchstartInInnerFrame:CommonTriggers.clickInInnerFrame;k.find(".js-titlesFilter").on("keyup",function(a){var c=$(a.currentTarget),b=c.parents("div[data-dropdown]"),d=b.find("[data-title]");c=c.parent().find(".js-titlesFilter__clear");var f=b.find(".c-dropdownMenu__empty"),g=b.find(".c-dropdownMenu__content"),e=b.find(".c-dropdownMenu__skiplink"),G=a.currentTarget.value;a.which==E&&a.preventDefault();a=a.currentTarget.value.toLowerCase();y(d,a)?
(f.hide(),g.show(),e.show()):(f.show(),g.hide(),e.hide());0===G.length?c.hide():c.show();b.find(".js-content").perfectScrollbar("update");b=coursesSortDropdownScope.kpi;CommonFunctions.measureKpi(b.url,b.section,b.measures.search,b.context)});k.find(".js-titlesFilter__clear").on(l,function(a){a.preventDefault();var c=$(a.currentTarget).parents("div[data-dropdown]");c.find("[data-title]").each(function(a,c){$(c).show()});c.find(".c-dropdownMenu__empty").hide();c.find(".c-dropdownMenu__content").show();
c.find(".js-titlesFilter").val("");c.find(".js-content").perfectScrollbar("update");$(this).hide();a.currentTarget.previousElementSibling.focus();return!1});k.children("a[data-action]").on(l,function(a){var c=$(a.currentTarget);if(!c.parents("li.l-more-menu-btn").length){a.preventDefault();var b=c.next();if(b.is(":visible"))b.hide(),$(".js-menuitem--dropdown.active div.active-shadow").show(),g=!1;else{$(".ccl-context-dialog").not(b).not(".static").hide();"false"===$(".c-messages-popup").attr("aria-hidden")&&
$(".c-messages__overlay").click();b.show();$(document).on(u,t);$("body").get(0).addEventListener(l,q,!0);(g=c.parent().hasClass("active"))?$(".js-menuitem--dropdown.active div.active-shadow").toggle():$(".js-menuitem--dropdown.active div.active-shadow").show();b.attr("aria-hidden",!1);$(".ccl-context-dialog").not(b).not(".static").attr("aria-hidden",!0);a=b.hasClass("js-onboarding");if(0<b.find(".js-content").length||p||a)(el=n(b))&&el.focus();else{p=!0;a=c.data("action");var d=b.find(".c-spinner-bounce"),
f=b.data("dropdown"),k=b.data("personid"),e=JSON.parse(localStorage.getItem(f+"_"+k));null!==e&&(f=b.find(".c-dropdown-toggle"),"undefined"!==typeof coursesSortDropdownScope&&f.html(coursesSortDropdownScope.langTerms[e.sortField]));$.get("/TopMenu/TopMenu/"+a).then(function(a){d.hide();b.append(a);a=b.find("[data-title]");var c=b.find(".js-titlesFilter");c.length&&""!==c.val()&&y(a,c.val().toLowerCase());5<a.length?(b.find(".c-search").css("visibility","visible"),b.find(".c-dropdown").css("visibility",
"visible")):e&&(e.sortField="lastUpdated");c=b.find(".js-content");c.perfectScrollbar({suppressScrollX:!0});c.find(".ps-scrollbar-y-rail").css("opacity",.6);c.find(".ps-scrollbar-y").attr("tabindex",-1);b.find(".js-content").perfectScrollbar("update");p=!1;$(".js-menuitem--dropdown").find(".c-dropdownMenu, .c-dropdownMenu__content").on(l,B);null!==e&&(c="title"===e.sortField?a.find('[data-column="lastUpdated"]'):a.find('[data-column="'+e.sortField+'"]'),c.siblings("[data-column]").each(A),c.each(z),
"title"===e.sortField?m(a,e.sortField):m(a,e.sortField,!0),a.detach().appendTo(b.find(".c-dropdownMenu__content > ul")));$firstEl=n(b);dropdownAttribute=b.data().dropdown;dropdownAttribute!=h.YourChildren?($allLink=b.find(".c-dropdownMenu__all:not(.c-dropdownMenu__skiplink)"),$allLink.keyup($firstEl,v),$firstEl.keyup($allLink,x)):($lastLink=b.find(".c-dropdownMenu__content > ul > li > a").last(),$lastLink.keyup($firstEl,v),$firstEl.keyup($lastLink,x));dropdownAttribute!=h.Courses&&dropdownAttribute!=
h.Projects&&b.find(".c-dropdownMenu__skiplink").hide();(el=n(b))&&el.focus()})}b.keyup({button:c,dropdown:b},C)}}});k.find(".c-dropdown > select").on("change",function(a){var c=a.currentTarget;a=$(c).parents(".c-dropdownMenu");var b=a.find("[data-title]"),d=a.data("dropdown"),f=a.data("personid");d=d+"_"+f;JSON.parse(localStorage.getItem(d));c=c.options[c.selectedIndex].value;localStorage.setItem(d,JSON.stringify({sortField:c}));d="title"===c?b.find('[data-column="lastUpdated"]'):b.find('[data-column="'+
c+'"]');d.siblings("[data-column]").each(A);d.each(z);"title"===c?m(b,c):m(b,c,!0);b.detach().appendTo(a.find(".c-dropdownMenu__content > ul"));a.find(".c-dropdown-menu").slideUp()});var H=new CCL.CallbackDebouncer(function(a){$(window).width()<=F&&hideDropDowns()});$(window).on("resize",function(){H.invokeCallback(null,100)})})();
